name: "NOSEA Marketplace Build and Deploy"

description: "This action builds and deploys the NOSEA Marketplace project to GitHub."

inputs:
  node-version:
    description: "The Node.js version to use for the build."
    required: true
    default: "18.x"
  
  branch:
    description: "The branch to deploy."
    required: true
    default: "main"

  github_token:
    description: "GitHub token for pushing the deployment."
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js Environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: "yarn"

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Build Application
      run: yarn build

    - name: Run Tests
      run: yarn test

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./.next

    - name: Deploy to GitHub Repository
      run: |
        git config --global user.name "wlplease"
        git config --global user.email "wlpleasenft@gmail.com"
        git remote add origin https://github.com/wlplease/onchain.git
        git fetch origin
        git checkout ${{ inputs.branch }}
        git add .
        git commit -m "Deploy from GitHub Actions"
        git push origin ${{ inputs.branch }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
