name: "NOSEA Marketplace Build and Deploy"

description: "This action builds and deploys the NOSEA Marketplace project to Netlify."

inputs:
  node-version:
    description: "The Node.js version to use for the build."
    required: true
    default: "18.x"
  
  branch:
    description: "The branch to deploy."
    required: true
    default: "main"

  netlify_auth_token:
    description: "Netlify authentication token."
    required: true
    default: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  netlify_site_id:
    description: "Netlify site ID for deployment."
    required: true
    default: ${{ secrets.NETLIFY_SITE_ID }}

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js Environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: "yarn"

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Build Application
      run: yarn build

    - name: Export Static Files (if applicable)
      run: yarn export

    - name: Deploy to Netlify
      uses: netlify/actions/cli@v1
      with:
        args: deploy --dir=.next --prod  # Adjust the directory if you're using 'out'
      env:
        NETLIFY_AUTH_TOKEN: ${{ inputs.netlify_auth_token }}
        NETLIFY_SITE_ID: ${{ inputs.netlify_site_id }}
