name: NOSEA Marketplace Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]  # Specify the Node.js version to use
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install OnchainKit Dependencies
        run: yarn add @coinbase/onchainkit

      - name: Build Application
        # Command to build the Next.js application
        run: yarn build

      - name: Run OnchainKit Tasks
        run: yarn onchainkit run
